package com.blogspot.pgoralik.gkim;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pawel
 */
public class DecoderUI extends javax.swing.JFrame {
    
    /**
     * Creates new form CoderUI
     */
    public DecoderUI() {
        initComponents();
        
        jFileChooserBMP.setFileFilter(new FileNameExtensionFilter("BMP", "bmp"));
        jFileChooserABMP.setFileFilter(new FileNameExtensionFilter("Alternative BMP", "abmp"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooserBMP = new javax.swing.JFileChooser();
        jFileChooserABMP = new javax.swing.JFileChooser();
        DekodujButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        PolozenieABMP = new javax.swing.JLabel();
        ABMPTextField = new javax.swing.JTextField();
        ABMPButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        PolozenieBMP = new javax.swing.JLabel();
        BMPTextField = new javax.swing.JTextField();
        BMPButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        BMPImage = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ABMP Dekoder - WIEiK PK GKiM Zespół 19");

        DekodujButton.setText("Dekoduj");
        DekodujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DekodujButtonActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Plik wejściowy ABMP"));

        PolozenieABMP.setText("Położenie:");

        ABMPButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/blogspot/pgoralik/gkim/res/dir.png"))); // NOI18N
        ABMPButton.setToolTipText("");
        ABMPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABMPButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PolozenieABMP)
                .addGap(3, 3, 3)
                .addComponent(ABMPTextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ABMPButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PolozenieABMP)
                    .addComponent(ABMPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ABMPButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Plik wyjściowy BMP"));

        PolozenieBMP.setText("Położenie:");

        BMPButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/blogspot/pgoralik/gkim/res/dir.png"))); // NOI18N
        BMPButton.setToolTipText("");
        BMPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMPButtonActionPerformed(evt);
            }
        });

        BMPImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jScrollPane1.setViewportView(BMPImage);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(PolozenieBMP)
                        .addGap(3, 3, 3)
                        .addComponent(BMPTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BMPButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PolozenieBMP)
                    .addComponent(BMPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BMPButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addContainerGap())
        );

        jProgressBar1.setStringPainted(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DekodujButton))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DekodujButton)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DekodujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DekodujButtonActionPerformed
        DekodujButton.setEnabled(false);
        
        new Decoder().execute(ABMPTextField.getText(), BMPTextField.getText());
    }//GEN-LAST:event_DekodujButtonActionPerformed

    private void ABMPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABMPButtonActionPerformed
        String dir = new File(System.getProperty("java.class.path")).getParent() + "/ ";
        jFileChooserABMP.setSelectedFile(new File(dir));
        int result = jFileChooserABMP.showOpenDialog(this);
        if(result ==  JFileChooser.APPROVE_OPTION) {
            File abmpPath = jFileChooserABMP.getSelectedFile();
            ABMPTextField.setText(abmpPath.toString());
            String initialPathToOutput = abmpPath.toString().split(".abmp")[0];
            initialPathToOutput += ".bmp";
            BMPTextField.setText(initialPathToOutput);
        }
    }//GEN-LAST:event_ABMPButtonActionPerformed

    private void BMPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMPButtonActionPerformed
        String dir = new File(System.getProperty("java.class.path")).getParent() + "/ ";
        jFileChooserBMP.setSelectedFile(new File(dir));
        String s = BMPTextField.getText();
        if(s != null)
            jFileChooserBMP.setSelectedFile(new File(s));
        int result = jFileChooserBMP.showSaveDialog(this);
        if(result ==  JFileChooser.APPROVE_OPTION) {
            File bmpPath = jFileChooserBMP.getSelectedFile();
            BMPTextField.setText(bmpPath.toString());
        }
    }//GEN-LAST:event_BMPButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DecoderUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DecoderUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DecoderUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DecoderUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new DecoderUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ABMPButton;
    private javax.swing.JTextField ABMPTextField;
    private javax.swing.JButton BMPButton;
    public static javax.swing.JLabel BMPImage;
    private javax.swing.JTextField BMPTextField;
    public static javax.swing.JButton DekodujButton;
    private javax.swing.JLabel PolozenieABMP;
    private javax.swing.JLabel PolozenieBMP;
    private javax.swing.JFileChooser jFileChooserABMP;
    private javax.swing.JFileChooser jFileChooserBMP;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
